const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      image: '/Images/product_1.jpg',
      price: 20,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt from Nike lately spring collection',
    },
    {
      _id: '2',
      name: 'Adidas Slim Shirt',
      image: '/Images/product_2.jpg',
      price: 22,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 11,
      description: 'high quality shirt from Adidas lately spring collection',
    },
    {
      _id: '3',
      name: 'C&A Slim Shirt',
      image: '/Images/product_3.jpg',
      price: 18,
      brand: 'C&A',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt from C&A lately spring collection',
    },
    {
      _id: '4',
      name: 'Nike Slim Shirt',
      image: '/Images/product_4.jpg',
      price: 25,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt from Nike lately spring collection',
    },
    {
      _id: '5',
      name: 'Nike Slim Shirt',
      image: '/Images/product_5.jpg',
      price: 25,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt from Nike lately spring collection',
    },
    {
      _id: '6',
      name: 'Nike Slim Shirt',
      image: '/Images/product_6.jpg',
      price: 25,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt from Nike lately spring collection',
    },
  ],
};

export default data;
